package gregtech.common.tileentities.machines.multi;

import gregtech.api.casing.Casings;
import gregtech.api.enums.Textures;
import gregtech.api.GregTechAPI;
import gregtech.api.interfaces.ITexture;
import gregtech.api.interfaces.metatileentity.IMetaTileEntity;
import gregtech.api.interfaces.tileentity.IGregTechTileEntity;
import gregtech.api.render.TextureFactory;
import gregtech.api.util.GTUtility;
import gregtech.api.util.MultiblockTooltipBuilder;

import gregtech.common.misc.GTStructureChannels;

import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.ForgeDirection;

import com.gtnewhorizon.structurelib.alignment.constructable.ISurvivalConstructable;
import com.gtnewhorizon.structurelib.structure.IStructureDefinition;
import com.gtnewhorizon.structurelib.structure.ISurvivalBuildEnvironment;
import com.gtnewhorizon.structurelib.structure.StructureDefinition;

import static com.gtnewhorizon.structurelib.structure.StructureUtility.ofBlock;
import static com.gtnewhorizon.structurelib.structure.StructureUtility.onElementPass;
import static gregtech.api.enums.HatchElement.Energy;
import static gregtech.api.enums.HatchElement.ExoticEnergy;
import static gregtech.api.enums.HatchElement.InputBus;
import static gregtech.api.enums.HatchElement.InputHatch;
import static gregtech.api.enums.HatchElement.OutputBus;
import static gregtech.api.enums.HatchElement.OutputHatch;
import static gregtech.api.enums.Textures.BlockIcons.OVERLAY_FRONT_MULTI_BREWERY;
import static gregtech.api.enums.Textures.BlockIcons.OVERLAY_FRONT_MULTI_BREWERY_ACTIVE;
import static gregtech.api.enums.Textures.BlockIcons.OVERLAY_FRONT_MULTI_BREWERY_ACTIVE_GLOW;
import static gregtech.api.enums.Textures.BlockIcons.OVERLAY_FRONT_MULTI_BREWERY_GLOW;
import static gregtech.api.util.GTStructureUtility.buildHatchAdder;


public class MTEGalactus extends MTEExtendedPowerMultiBlockBase<MTEGalactus> implements ISurvivalConstructable {

    private static final String STRUCTURE_PIECE_MAIN = "main";

    private static final IStructureDefinition<MTEGalactus> STRUCTURE_DEFINITION = StructureDefinition
        .<MTEGalactus>builder()
        .addShape(
            STRUCTURE_PIECE_MAIN,
            // spotless:off
            new String[][]{{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "                         ",
                " DDDD               DDDD "
            },{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  C                      ",
                " C                     C ",
                "                      C  ",
                "   C                 C   ",
                "  C                      ",
                " C                     C ",
                "                      C  ",
                "   C                 C   ",
                "  C                      ",
                " C                     C ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D       FFFFFFF       D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D       FFFFFFF       D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D       FFFFFFF       D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D                     D ",
                " DDD                 DDD ",
                "DDGGDD             DDGGDD"
            },{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  K                   K  ",
                "  G                  CGC ",
                "  G                   G  ",
                " CGC                  G  ",
                "  G                   G  ",
                "  G                  CGC ",
                "  G                   G  ",
                " CGC                  G  ",
                "  G                   G  ",
                "  G                  CGC ",
                "  G                   G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G    FF       FF    G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G    FF       FF    G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G    FF       FF    G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  DD                 DD  ",
                " DGDD               DGGD ",
                "DGFFDD             DDFFGD"
            },{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          BBBBB          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  C                      ",
                "   C                 C   ",
                "                      C  ",
                " C                     C ",
                "  C                      ",
                "   C                 C   ",
                "                      C  ",
                " C                     C ",
                "  C                      ",
                "   C                 C   ",
                " FFADFFDD       DDFFDAFF ",
                "   A FF           FF A   ",
                " FFADFFDD       DDFFDAFF ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                " FFADFFDD       DDFFDAFF ",
                "   A FF           FF A   ",
                " FFADFFDD       DDFFDAFF ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                " FFADFFDD       DDFFDAFF ",
                "   A FF           FF A   ",
                " FFADFFDD       DDFFDAFF ",
                "  DAD               DAD  ",
                " DGAD               DAGD ",
                "DGFADD             DDAFGD"
            },{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          HHHHH          ",
                "          HHHHH          ",
                "        BBHHHHHBB        ",
                "          HHHHH          ",
                "          HHHHH          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "   DFDD           DDFD   ",
                "    F               F    ",
                "   DFDD           DDFD   ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "   DFDD           DDFD   ",
                "    F               F    ",
                "   DFDD           DDFD   ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "   DFDD           DDFD   ",
                "    F               F    ",
                "   DFDD           DDFD   ",
                "   DFD             DFD   ",
                "  DDD               DDD  ",
                "DDDDDD             DDDDDD"
            },{
                "                         ",
                "                         ",
                "                         ",
                "         BBBBBBB         ",
                "          HHHHH          ",
                "         HHHHHHH         ",
                "        HH     HH        ",
                "        HH     HH        ",
                "       BHH     HHB       ",
                "        HH     HH        ",
                "        HH     HH        ",
                "         HHHHHHH         ",
                "          HHHHH          ",
                "         BBBBBBB         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD               DFD  ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD               DFD  ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD               DFD  ",
                "    DFD           DFD    ",
                "                         ",
                " DDDD               DDDD "
            },{
                "                         ",
                "                         ",
                "            H            ",
                "        BHHHHHHHB        ",
                "        HH     HH        ",
                "       HH       HH       ",
                "       H         H       ",
                "       H         H       ",
                "      BH         HB      ",
                "       H         H       ",
                "       H         H       ",
                "       HH       HH       ",
                "        HH     HH        ",
                "        BHHHHHHHB        ",
                "            H            ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD               DFD  ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "                         ",
                "  DFD DDDDDDDDDDDDD DFD  ",
                "   F                 F   ",
                "  DFD DDDDDDDDDDDDD DFD  ",
                "                         ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD     GGGGG     DFD  ",
                "     DFD  F   F  DFD     ",
                "          F   F          ",
                "          F   F          "
            },{
                "                         ",
                "                         ",
                "         HHHHHHH         ",
                "       BH       HB       ",
                "       H         H       ",
                "      H           H      ",
                "      H           H      ",
                "      H           H      ",
                "     BH           HB     ",
                "      H           H      ",
                "      H           H      ",
                "      H           H      ",
                "       H         H       ",
                "       BH       HB       ",
                "         HHHHHHH         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD                 DFD ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD                 DFD ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD    GG     GG    DFD ",
                "      DFDF     FDFD      ",
                "         F     F         ",
                "         F     F         "
            },{
                "                         ",
                "          HHHHH          ",
                "        HH     HH        ",
                "      BH         HB      ",
                "      H           H      ",
                "      H           H      ",
                "     H             H     ",
                "     H             H     ",
                "    BH             HB    ",
                "     H             H     ",
                "     H             H     ",
                "      H           H      ",
                "      H           H      ",
                "      BH         HB      ",
                "        HH     HH        ",
                "          HHHHH          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD                 DFD ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD                 DFD ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD   G         G   DFD ",
                "       DFD     DFD       ",
                "        F       F        ",
                "        F       F        "
            },{
                "                         ",
                "         HHHHHHH         ",
                "       HH       HH       ",
                "     BH           HB     ",
                "      H           H      ",
                "     H             H     ",
                "     H             H     ",
                "     H             H     ",
                "    BH             HB    ",
                "     H             H     ",
                "     H             H     ",
                "     H             H     ",
                "      H           H      ",
                "     BH           HB     ",
                "       HH       HH       ",
                "         HHHHHHH         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "DFD      GGGGGGG      DFD",
                " F                     F ",
                "DFD      GGGGGGG      DFD",
                "                         ",
                "         GGGGGGG         ",
                "                         ",
                "         GGGGGGG         ",
                "                         ",
                "      D  GGGGGGG  D      ",
                "                         ",
                "         GGGGGGG         ",
                "      D           D      ",
                "         GGGGGGG         ",
                "                         ",
                "      D  GGGGGGG  D      ",
                "                         ",
                "DFD      GGGGGGG      DFD",
                " F                     F ",
                "DFD      GGGGGGG      DFD",
                "                         ",
                "      D  GGGGGGG  D      ",
                "                         ",
                "         GGGGGGG         ",
                "      D           D      ",
                "         GGGGGGG         ",
                "                         ",
                "      D  GGGGGGG  D      ",
                "                         ",
                "         GGGGGGG         ",
                "                         ",
                "         GGGGGGG         ",
                "                         ",
                "DFD      GGGGGGG      DFD",
                " F                     F ",
                "DFD    G         G    DFD",
                "       FDFD   DFDF       ",
                "       F  F   F  F       ",
                "       F  F   F  F       "
            },{
                "          HHHHH          ",
                "        HH     HH        ",
                "       H         H       ",
                "     BH           HB     ",
                "     H             H     ",
                "     H             H     ",
                "    H               H    ",
                "    H               H    ",
                "   BH               HB   ",
                "    H               H    ",
                "    H               H    ",
                "     H             H     ",
                "     H             H     ",
                "     BH           HB     ",
                "       H         H       ",
                "        HH     HH        ",
                "          HHHHH          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           JJJ           ",
                "DFD      GIJJJIG      DFD",
                " F        IJJJI        F ",
                "DFD      GIJJJIG      DFD",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "      D  GIJJJIG  D      ",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "      D   IJJJI   D      ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "      D  GIJJJIG  D      ",
                "          IJJJI          ",
                "DFD      GIJJJIG      DFD",
                " F        IJJJI        F ",
                "DFD      GIJJJIG      DFD",
                "          IJJJI          ",
                "      D  GIJJJIG  D      ",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "      D   IJJJI   D      ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "      D  GIJJJIG  D      ",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "DFD      GIJJJIG      DFD",
                " F        IJJJI        F ",
                "DFD   G   IJJJI   G   DFD",
                "      F  DIDDDID  F      ",
                "      F  FIL~LIF  F      ",
                "      F  FILLLIF  F      "
            },{
                "          HHHHH          ",
                "        HH     HH        ",
                "       H         H       ",
                "     BH           HB     ",
                "     H             H     ",
                "     H             H     ",
                "    H               H    ",
                "    H               H    ",
                "   BH               HB   ",
                "    H               H    ",
                "    H               H    ",
                "     H             H     ",
                "     H             H     ",
                "     BH           HB     ",
                "       H         H       ",
                "        HH     HH        ",
                "          HHHHH          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            I            ",
                "            I            ",
                "           IJI           ",
                "           IJI           ",
                "          JEEEJ          ",
                "DFD      GJEEEJG      DFD",
                " F        JEEEJ        F ",
                "DFD      GJEEEJG      DFD",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "      D   JEEEJ   D      ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "      D  GJEEEJG  D      ",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "      D   JEEEJ   D      ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "DFD      GJEEEJG      DFD",
                " F        JEEEJ        F ",
                "DFD      GJEEEJG      DFD",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "      D   JEEEJ   D      ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "      D  GJEEEJG  D      ",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "      D   JEEEJ   D      ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "DFD      GJEEEJG      DFD",
                " F        JEEEJ        F ",
                "DFD   G   JEEEJ   G   DFD",
                "          DJJJD          ",
                "          GDDDG          ",
                "          GDDDG          "
            },{
                "          HHHHH          ",
                "        HH     HH        ",
                "      HH         HH      ",
                "     BH           HB     ",
                "     H             H     ",
                "     H             H     ",
                "    H               H    ",
                "    H               H    ",
                "   BH       G       HB   ",
                "    H               H    ",
                "    H               H    ",
                "     H             H     ",
                "     H             H     ",
                "     BH           HB     ",
                "      HH         HH      ",
                "        HH     HH        ",
                "          HHHHH          ",
                "                         ",
                "                         ",
                "                         ",
                "            K            ",
                "            I            ",
                "            I            ",
                "           IJI           ",
                "           IJI           ",
                "           JJJ           ",
                "           JJJ           ",
                "          JEJEJ          ",
                "DFD      GJEJEJG      DFD",
                " F        JEJEJ        F ",
                "DFD      GJEJEJG      DFD",
                "          JEJEJ          ",
                "         GJEJEJG         ",
                "          JEJEJ          ",
                "         GJEJEJG         ",
                "      D   JEJEJ   D      ",
                "         GJEJEJG         ",
                "          JEJEJ          ",
                "      D  GJEJEJG  D      ",
                "          JEJEJ          ",
                "         GJEJEJG         ",
                "      D   JEJEJ   D      ",
                "         GJEJEJG         ",
                "          JEJEJ          ",
                "DFD      GJEJEJG      DFD",
                " F        JEJEJ        F ",
                "DFD      GJEJEJG      DFD",
                "          JEJEJ          ",
                "         GJEJEJG         ",
                "      D   JEJEJ   D      ",
                "         GJEJEJG         ",
                "          JEJEJ          ",
                "      D  GJEJEJG  D      ",
                "          JEJEJ          ",
                "         GJEJEJG         ",
                "      D   JEJEJ   D      ",
                "         GJEJEJG         ",
                "          JEJEJ          ",
                "         GJEJEJG         ",
                "          JEJEJ          ",
                "DFD      GJEJEJG      DFD",
                " F        JEJEJ        F ",
                "DFD   G   JEJEJ   G   DFD",
                "          DJJJD          ",
                "          GDDDG          ",
                "          GDDDG          "
            },{
                "          HHHHH          ",
                "        HH     HH        ",
                "       H         H       ",
                "     BH           HB     ",
                "     H             H     ",
                "     H             H     ",
                "    H               H    ",
                "    H               H    ",
                "   BH               HB   ",
                "    H               H    ",
                "    H               H    ",
                "     H             H     ",
                "     H             H     ",
                "     BH           HB     ",
                "       H         H       ",
                "        HH     HH        ",
                "          HHHHH          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            I            ",
                "            I            ",
                "           IJI           ",
                "           IJI           ",
                "          JEEEJ          ",
                "DFD      GJEEEJG      DFD",
                " F        JEEEJ        F ",
                "DFD      GJEEEJG      DFD",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "      D   JEEEJ   D      ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "      D  GJEEEJG  D      ",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "      D   JEEEJ   D      ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "DFD      GJEEEJG      DFD",
                " F        JEEEJ        F ",
                "DFD      GJEEEJG      DFD",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "      D   JEEEJ   D      ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "      D  GJEEEJG  D      ",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "      D   JEEEJ   D      ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "         GJEEEJG         ",
                "          JEEEJ          ",
                "DFD      GJEEEJG      DFD",
                " F        JEEEJ        F ",
                "DFD   G   JEEEJ   G   DFD",
                "          DJJJD          ",
                "          GDDDG          ",
                "          GDDDG          "
            },{
                "          HHHHH          ",
                "        HH     HH        ",
                "       H         H       ",
                "     BH           HB     ",
                "     H             H     ",
                "     H             H     ",
                "    H               H    ",
                "    H               H    ",
                "   BH               HB   ",
                "    H               H    ",
                "    H               H    ",
                "     H             H     ",
                "     H             H     ",
                "     BH           HB     ",
                "       H         H       ",
                "        HH     HH        ",
                "          HHHHH          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           JJJ           ",
                "DFD      GIJJJIG      DFD",
                " F        IJJJI        F ",
                "DFD      GIJJJIG      DFD",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "      D  GIJJJIG  D      ",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "      D   IJJJI   D      ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "      D  GIJJJIG  D      ",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "DFD      GIJJJIG      DFD",
                " F        IJJJI        F ",
                "DFD      GIJJJIG      DFD",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "      D  GIJJJIG  D      ",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "      D   IJJJI   D      ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "      D  GIJJJIG  D      ",
                "          IJJJI          ",
                "         GIJJJIG         ",
                "          IJJJI          ",
                "DFD      GIJJJIG      DFD",
                " F        IJJJI        F ",
                "DFD   G   IJJJI   G   DFD",
                "      F  DIDDDID  F      ",
                "      F   ILLLIF  F      ",
                "      F   ILLLIF  F      "
            },{
                "                         ",
                "         HHHHHHH         ",
                "       HH       HH       ",
                "     BH           HB     ",
                "      H           H      ",
                "     H             H     ",
                "     H             H     ",
                "     H             H     ",
                "    BH             HB    ",
                "     H             H     ",
                "     H             H     ",
                "     H             H     ",
                "      H           H      ",
                "     BH           HB     ",
                "       HH       HH       ",
                "         HHHHHHH         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "DFD      GGGGGGG      DFD",
                " F                     F ",
                "DFD      GGGGGGG      DFD",
                "                         ",
                "         GGGGGGG         ",
                "                         ",
                "      D  GGGGGGG  D      ",
                "                         ",
                "         GGGGGGG         ",
                "      D           D      ",
                "         GGGGGGG         ",
                "                         ",
                "      D  GGGGGGG  D      ",
                "                         ",
                "         GGGGGGG         ",
                "                         ",
                "DFD      GGGGGGG      DFD",
                " F                     F ",
                "DFD      GGGGGGG      DFD",
                "                         ",
                "         GGGGGGG         ",
                "                         ",
                "      D  GGGGGGG  D      ",
                "                         ",
                "         GGGGGGG         ",
                "      D           D      ",
                "         GGGGGGG         ",
                "                         ",
                "      D  GGGGGGG  D      ",
                "                         ",
                "         GGGGGGG         ",
                "                         ",
                "DFD      GGGGGGG      DFD",
                " F                     F ",
                "DFD    G         G    DFD",
                "       FDFD   DFDF       ",
                "       F      F  F       ",
                "       F      F  F       "
            },{
                "                         ",
                "          HHHHH          ",
                "        HH     HH        ",
                "      BH         HB      ",
                "      H           H      ",
                "      H           H      ",
                "     H             H     ",
                "     H             H     ",
                "    BH             HB    ",
                "     H             H     ",
                "     H             H     ",
                "      H           H      ",
                "      H           H      ",
                "      BH         HB      ",
                "        HH     HH        ",
                "          HHHHH          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD                 DFD ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD                 DFD ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD   G         G   DFD ",
                "       DFD     DFD       ",
                "        F       F        ",
                "        F       F        "
            },{
                "                         ",
                "                         ",
                "         HHHHHHH         ",
                "       BH       HB       ",
                "       H         H       ",
                "      H           H      ",
                "      H           H      ",
                "      H           H      ",
                "     BH           HB     ",
                "      H           H      ",
                "      H           H      ",
                "      H           H      ",
                "       H         H       ",
                "       BH       HB       ",
                "         HHHHHHH         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD                 DFD ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD                 DFD ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                "      D           D      ",
                "                         ",
                "                         ",
                " DFD                 DFD ",
                "  F                   F  ",
                " DFD    GG     GG    DFD ",
                "      DFDF     FDFD      ",
                "         F     F         ",
                "         F     F         "
            },{
                "                         ",
                "                         ",
                "            H            ",
                "        BHHHHHHHB        ",
                "        HH     HH        ",
                "       HH       HH       ",
                "       H         H       ",
                "       H         H       ",
                "      BH         HB      ",
                "       H         H       ",
                "       H         H       ",
                "       HH       HH       ",
                "        HH     HH        ",
                "        BHHHHHHHB        ",
                "            H            ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD               DFD  ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD               DFD  ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "                         ",
                "      DDDDDDDDDDDDD      ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD     GGGGG     DFD  ",
                "     DFD  F   F  DFD     ",
                "          F   F          ",
                "          F   F          "
            },{
                "                         ",
                "                         ",
                "                         ",
                "         BBBBBBB         ",
                "          HHHHH          ",
                "         HHHHHHH         ",
                "        HH     HH        ",
                "        HH     HH        ",
                "       BHH     HHB       ",
                "        HH     HH        ",
                "        HH     HH        ",
                "         HHHHHHH         ",
                "          HHHHH          ",
                "         BBBBBBB         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD               DFD  ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD               DFD  ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  DFD               DFD  ",
                "   F                 F   ",
                "  DFD               DFD  ",
                "    DFD           DFD    ",
                "                         ",
                " DDDD               DDDD "
            },{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          HHHHH          ",
                "          HHHHH          ",
                "        BBHHHHHBB        ",
                "          HHHHH          ",
                "          HHHHH          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "   DFDD           DDFD   ",
                "    F               F    ",
                "   DFDD           DDFD   ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "   DFDD           DDFD   ",
                "    F               F    ",
                "   DFDD           DDFD   ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "   DFDD           DDFD   ",
                "    F               F    ",
                "   DFDD           DDFD   ",
                "   DFD             DFD   ",
                "  DDD               DDDD ",
                "DDDDDD             DDDDDD"
            },{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          BBBBB          ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                      C  ",
                "   C                 C   ",
                "  C                      ",
                " C                     C ",
                "                      C  ",
                "   C                 C   ",
                "  C                      ",
                " C                     C ",
                "                      C  ",
                "   C                 C   ",
                " FFADFFDD       DDFFDAFF ",
                "   A FF           FF A   ",
                " FFADFFDD       DDFFDAFF ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                " FFADFFDD       DDFFDAFF ",
                "   A FF           FF A   ",
                " FFADFFDD       DDFFDAFF ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                "   A                 A   ",
                " FFADFFDD       DDFFDAFF ",
                "   A FF           FF A   ",
                " FFADFFDD       DDFFDAFF ",
                "  DAD               DAD  ",
                " DGAD               DAGD ",
                "DGFADD             DDAFGD"
            },{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "  K                   K  ",
                " CGC                  G  ",
                "  G                   G  ",
                "  G                  CGC ",
                "  G                   G  ",
                " CGC                  G  ",
                "  G                   G  ",
                "  G                  CGC ",
                "  G                   G  ",
                " CGC                  G  ",
                "  G                   G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G    FF       FF    G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G    FF       FF    G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  G                   G  ",
                "  GF                  G  ",
                "  G                   G  ",
                "  G                   G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  G    FF       FF    G  ",
                " FGF DDFFDDDDDDDFFDD FGF ",
                "  DD                 DD  ",
                " DGGD               DGGD ",
                "DGFFDD             DDFFGD"
            },{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                      C  ",
                " C                     C ",
                "  C                      ",
                "   C                 C   ",
                "                      C  ",
                " C                     C ",
                "  C                      ",
                "   C                 C   ",
                "                      C  ",
                " C                     C ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D       FFFFFFF       D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D       FFFFFFF       D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " D                     D ",
                " DFF                   D ",
                " D                     D ",
                " D                     D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D       FFFFFFF       D ",
                " DFF   DDFFFFFFFDD   FFD ",
                " D                     D ",
                " DDD                 DDD ",
                "DDGGDD             DDGGDD"
            },{
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "         DDDDDDD         ",
                "                         ",
                "                         ",
                " DDDD               DDDD "
            }})
        // spotless:on
        //Temporary Casings
        .addElement('A', Casings.NaquadahReactorCasing.asElement()) //advanced SE orbits, black
        .addElement('B', Casings.NaquadahReactorCasing.asElement()) //restrainer frames, black
        .addElement('C', Casings.NaquadahReactorCasing.asElement()) //totem, black-grey
        .addElement('D', Casings.NaquadahReactorCasing.asElement()) //black casing
        .addElement('E', Casings.NaquadahReactorCasing.asElement()) //coil
        .addElement('F', Casings.NaquadahReactorCasing.asElement()) //white casing
        .addElement('G', Casings.NaquadahReactorCasing.asElement()) //yellow casing & outside coil
        .addElement('H', Casings.NaquadahReactorCasing.asElement()) //glass
        .addElement('I', Casings.NaquadahReactorCasing.asElement()) //black pillar
        .addElement('J', Casings.NaquadahReactorCasing.asElement()) //red casing, use exo's
        .addElement('K', Casings.NaquadahReactorCasing.asElement()) //siphon, use gorge's
        .addElement(
            'L', // refering to 'G'
            buildHatchAdder(MTEGalactus.class)
                .atLeast(InputBus, OutputBus, InputHatch, OutputHatch)
                .dot(1)
                .casingIndex(Casings.NaquadahReactorCasing.textureId)
                .buildAndChain(
                    onElementPass(MTEGalactus::onCasingAdded, Casings.NaquadahReactorCasing.asElement())))
        .build();
    
    public MTEGalactus(final int aID, final String aName, final String aNameRegional) {
        super(aID, aName, aNameRegional);
    }

    public MTEGalactus(String aName) {
        super(aName);
    }

    @Override
    public IStructureDefinition<MTEGalactus> getStructureDefinition() {
        return STRUCTURE_DEFINITION;
    }

    @Override
    public IMetaTileEntity newMetaEntity(IGregTechTileEntity aTileEntity) {
        return new MTEGalactus(this.mName);
    }

    //ALL TEMPORARY DOWNSIDE
    @Override
    public ITexture[] getTexture(IGregTechTileEntity baseMetaTileEntity, ForgeDirection side, ForgeDirection aFacing,
                                 int colorIndex, boolean aActive, boolean redstoneLevel) {
        ITexture[] rTexture;
        if (side == aFacing) {
            if (aActive) {
                rTexture = new ITexture[] {
                    Textures.BlockIcons
                        .getCasingTextureForId(GTUtility.getCasingTextureIndex(GregTechAPI.sBlockCasings13, 15)),
                    TextureFactory.builder()
                        .addIcon(OVERLAY_FRONT_MULTI_BREWERY_ACTIVE)
                        .extFacing()
                        .build(),
                    TextureFactory.builder()
                        .addIcon(OVERLAY_FRONT_MULTI_BREWERY_ACTIVE_GLOW)
                        .extFacing()
                        .glow()
                        .build() };
            } else {
                rTexture = new ITexture[] {
                    Textures.BlockIcons
                        .getCasingTextureForId(GTUtility.getCasingTextureIndex(GregTechAPI.sBlockCasings13, 15)),
                    TextureFactory.builder()
                        .addIcon(OVERLAY_FRONT_MULTI_BREWERY)
                        .extFacing()
                        .build(),
                    TextureFactory.builder()
                        .addIcon(OVERLAY_FRONT_MULTI_BREWERY_GLOW)
                        .extFacing()
                        .glow()
                        .build() };
            }
        } else {
            rTexture = new ITexture[] { Textures.BlockIcons
                .getCasingTextureForId(GTUtility.getCasingTextureIndex(GregTechAPI.sBlockCasings13, 15)) };
        }
        return rTexture;
    }

    @Override
    protected MultiblockTooltipBuilder createTooltip() {
        MultiblockTooltipBuilder tt = new MultiblockTooltipBuilder();
        tt.addMachineType("Brewery")
            .addBulkMachineInfo(4, 1.5F, 1F)
            .beginStructureBlock(3, 5, 3, true)
            .addController("Front Center")
            .addCasingInfoMin("Reinforced Wooden Casing", 14, false)
            .addCasingInfoExactly("Any Tiered Glass", 6, false)
            .addCasingInfoExactly("Steel Frame Box", 4, false)
            .addInputBus("Any Wooden Casing", 1)
            .addOutputBus("Any Wooden Casing", 1)
            .addInputHatch("Any Wooden Casing", 1)
            .addOutputHatch("Any Wooden Casing", 1)
            .addEnergyHatch("Any Wooden Casing", 1)
            .addMaintenanceHatch("Any Wooden Casing", 1)
            .addSubChannelUsage(GTStructureChannels.BOROGLASS)
            .toolTipFinisher();
        return tt;
    }

    @Override
    public void construct(ItemStack stackSize, boolean hintsOnly) {
        buildPiece(STRUCTURE_PIECE_MAIN, stackSize, hintsOnly, 54, 4, 1);
    }

    @Override
    public int survivalConstruct(ItemStack stackSize, int elementBudget, ISurvivalBuildEnvironment env) {
        if (mMachine) return -1;
        return survivalBuildPiece(STRUCTURE_PIECE_MAIN, stackSize, 1, 2, 0, elementBudget, env, false, true);
    }

    private int mCasingAmount;

    private void onCasingAdded() {
        mCasingAmount++;
    }

    @Override
    public boolean checkMachine(IGregTechTileEntity aBaseMetaTileEntity, ItemStack aStack) {
        mCasingAmount = 0;
        return checkPiece(STRUCTURE_PIECE_MAIN, 1, 2, 0) && mCasingAmount >= 14;
    }

}
